### ISSUE TITLE
commit messages don't show up

### ISSUE THREAD

**Issue by VladimirAlexiev** [tbeu/WDX_GitCommander#1]
@tbeu Thanks for the 64-bit version!
I explored the available fields with "WDXGuide" and noticed the following problem:

cc @Darthholi 

![image](https://user-images.githubusercontent.com/536250/106501052-3f6a4580-64cb-11eb-8b1b-a90ae7e834db.png)

As you see in `FullDescription`, there is a commit message "GET-71....". 
But it doesn't show up in any of the fields `CommitMessage, LastMessage, FallMessage`.

Could you also explain what is the difference between them? From the readme it seems `FallMessage` is the message in the "Last commit affecting given file"?

Also, `FileStatus, GeneralStatus` always seem to be "unchanged", is that how it should be?

**Comment by tbeu** [comment]
* I can confirm the issues with empty commit messages.
* I can't confirm the issue about the file status.

**Comment by tbeu** [comment]
EDIT. See above.

**Comment by tbeu** [comment]
Resolved in v2.0.1.
